import './global.css';
import { ClusterProvider } from '@/components/solana/cluster-data-access';
import { SolanaProvider, WalletButton } from '@/components/solana/solana-provider';
import { ReactQueryProvider } from './react-query-provider';
import Image from 'next/image';

export const metadata = {
  title: 'web-app',
  description: 'Generated by create-solana-dapp',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <div style={{ flex: '0 0 auto' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: 30 }}>
                  <Image 
                    src="/logo.svg" 
                    alt="Quartz" 
                    width={150} 
                    height={52}
                  />
                  <WalletButton />
                </div>
              </div>
              <main style={{ flex: '1 0 auto', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                {children}
              </main>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
