export enum AccountStatus {
    DISCONNECTED = "DISCONNECTED",
    NO_BETA_KEY = "NO_BETA_KEY",
    NOT_INITIALIZED = "NOT_INITIALIZED",
    INITIALIZED = "INITIALIZED",
    CLOSED = "CLOSED",
    UPGRADE_REQUIRED = "UPGRADE_REQUIRED"
}
