export enum ModalVariation {
    DISABLED = "DISABLED",
    NOTIFICATIONS = "NOTIFICATIONS",
    ADD_FUNDS = "ADD_FUNDS",
    WITHDRAW = "WITHDRAW",  
    BORROW = "BORROW",
    REPAY = "REPAY",
    REPAY_LOAN = "REPAY_LOAN",
    CLOSE_ACCOUNT = "CLOSE_ACCOUNT",
    CARD_SIGNUP = "CARD_SIGNUP"
}